appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: QPCJxMIZjti3ZfU3PRvJmisAk/TsTN2VFtWpJJK0lp8JqcNQeMMXCGrEbvFyWIingaI1QpNrQ9fkHEqzL0dedYNE+s05RdCqxIlkRbrfyvpbZ6rfPl4cKfPELL8rI7UQfov9jN3xxa0sUf6Vv+Cfqz/R3w/0SkUJL0Q7P9SCvdqeRCHxXEdDS1dXuwNr2NoupsqXKRrLrzAY63DyDo5PdBkOJ1hOJZhw56XbUKcsKSfJfNHMblXy+TOuzDYd5CYnLcYLygbCVc3KL+36iW8FbI2dwsDBZOa8pJHts1M1cMX4wscvC3an3vTYGpn/ZyFq6g0E/MT2zGy4qJNQoAxTpqkQTIuGr0XKJR5qAE9hQ+EBxi4WT5Xz12TwS9xRApvVCAqqsfsDOZlvb0Y+Z65fM1+YlZrsRXDsVsfdUkl/y1Mr8+9QSI7Mb5kYliReLiDAhH9I4ml3OduWW6s9vkyn77xgtoRWTuKIaEvXCNREYpRLmbodPS1K5FVfCvWoQSgly40Sk7aUbCDZifEfrYN8e8dc1WUc0SU1s9Y6vCkshF3sZht6Hzdv0ukfBZxTTZLUaqoGaohPlKxgO71tloIFTXr2dsQ7BQv1mP8LtJUBnjm3W5PhKB3YB8TLubkVsx92y7y1KBZTmL8SrYzkKiLO+wJLAPMYdrfLhI7n5wSotXI=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
